// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var ui;
    $.validator.addMethod('decimal', function(value, element) {
      return this.optional(element) || /^[0-9,]+(\.\d{0,3})?$/.test(value);
    }, "Лише цифри, формат xx.xxx");
    $(window).keydown(function(event) {
      if (event.keyCode === 13) {
        event.preventDefault();
        return false;
      }
    });
    $.extend($.validator.messages, {
      required: "Заповніть поле!",
      minlength: "Мін. {0} символи!"
    });
    utils.setServerCommunicator(serverCommunicator.getInstance());
    ui = {
      getUserLogin: function() {
        return $("#userlogin").val().trim().toLowerCase();
      },
      getUserPass: function() {
        return $("#userpass").val().trim().toLowerCase();
      },
      getUserLoginToDelete: function() {
        return $("#usertodelete").val();
      },
      getBuildingId: function() {
        return $("#streetid").val();
      },
      getUSDAdjust: function() {
        return $("#usdadjust").val();
      }
    };
    $('#saveuser').bind('click', function(e) {
      if ($("#newuserform").valid()) {
        return utils.postToServer("saveitem", {
          "collection": "users",
          "login": ui.getUserLogin(),
          "pass": ui.getUserPass()
        }, function(saved) {});
      }
    });
    $("#deleteuser").bind('click', function(e) {
      if ($("#deleteuserform").valid()) {
        return utils.postToServer("deleteuser", {
          "collection": "users",
          "login": ui.getUserLoginToDelete()
        }, function() {});
      }
    });
    $("#saveadjust").bind('click', function(e) {
      if ($("#usdadjustform").valid()) {
        return utils.postToServer("saveusdadjust", {
          "adjust": ui.getUSDAdjust()
        }, function() {});
      }
    });
    $("#deletebuilding").bind('click', function(e) {
      if ($("#deletebuildingform").valid()) {
        return utils.postToServer("deletebuilding", {
          "id": ui.getBuildingId()
        }, function() {});
      }
    });
    $("#newuserform").validate({
      rules: {
        userlogin: {
          required: true
        },
        userpass: {
          required: true
        }
      }
    });
    $("#deleteuserform").validate({
      rules: {
        usertodelete: {
          required: true
        }
      }
    });
    $("#deletebuildingform").validate({
      rules: {
        streetid: {
          required: true,
          minlength: 24
        }
      }
    });
    return $("#usdadjustform").validate({
      rules: {
        usdadjust: {
          required: true,
          decimal: true
        }
      }
    });
  });

}).call(this);
