// Generated by CoffeeScript 1.6.2
(function() {
  var ServerCommunicator;

  window.serverCommunicator = {};

  serverCommunicator.getInstance = function() {
    var serverCommunicator;

    serverCommunicator = new ServerCommunicator();
    return serverCommunicator;
  };

  ServerCommunicator = (function() {
    function ServerCommunicator() {}

    ServerCommunicator.prototype.createRequest = function(method, path, request_body, fn) {
      var _httpRequest;

      _httpRequest = new XMLHttpRequest();
      _httpRequest.onreadystatechange = function() {
        var data;

        if (_httpRequest.readyState === 4) {
          if (_httpRequest.status === 200) {
            data = JSON.parse(_httpRequest.responseText);
            return fn(data);
          } else {
            $("#serverMessages").addClass('alert-error');
            $("#serverMessages").text("Серверу не вдалось обробити запит!");
            $("#serverMessages").show();
            return setTimeout(function() {
              $("#serverMessages").fadeOut('slow');
              return $("#serverMessages").removeClass('alert-error');
            }, 3000);
          }
        }
      };
      _httpRequest.open(method, "http://127.0.0.1:8080/" + path, true);
      _httpRequest.setRequestHeader('Content-Type', 'application/json');
      return _httpRequest.send(request_body);
    };

    return ServerCommunicator;

  })();

}).call(this);
