// Generated by CoffeeScript 1.7.1
(function() {
  var accessToResourseAllowed, checkAccess;

  accessToResourseAllowed = function(login) {
    var result;
    result = false;
    if (login === 'victor' || login === 'chovgan' || login === 'admin') {
      result = true;
    }
    return result;
  };

  checkAccess = function(req, res, next) {
    if (!accessToResourseAllowed(req.session.login)) {
      return res.end("Access not allowed!");
    } else {
      return next();
    }
  };

  module.exports.checkAccess = checkAccess;

}).call(this);
