// Generated by CoffeeScript 1.6.2
(function() {
  var accessToResourseAllowed, checkAccess;

  accessToResourseAllowed = function(login) {
    var result;

    result = false;
    if (login === 'victor') {
      result = true;
    }
    return result;
  };

  checkAccess = function(req, res, next) {
    if (!accessToResourseAllowed(req.session.login)) {
      return res.send(JSON.stringify({
        result: "Ви не можете додавати дані"
      }));
    } else {
      return next();
    }
  };

  module.exports.checkAccess = checkAccess;

}).call(this);
