// Generated by CoffeeScript 1.6.2
(function() {
  var createBoxesStoreTableData, createCopperIncomeTableData, createOpticalIncomeTableData, createWareHouseLogsTableData, createpatchcordesStoreTableData, createpatchpanelesStoreTableData, createpigtailsesStoreTableData, createsocketsesStoreTableData;

  createCopperIncomeTableData = function(items) {
    var count, field, fields, i, rowdata, values, _i, _j, _len, _len1;

    fields = ["type", "pairs", "rope", "manufacturer", "serial", "length"];
    values = [];
    count = 1;
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      i = items[_i];
      if (i.length !== 0) {
        rowdata = [];
        rowdata.push(count);
        for (_j = 0, _len1 = fields.length; _j < _len1; _j++) {
          field = fields[_j];
          rowdata.push(i[field]);
        }
        values.push(rowdata);
        count++;
      }
    }
    return {
      "title": 'Звита пара',
      "headers": ['№', 'Тип', 'К-сть пар', 'Трос', 'Виробник', 'Серійний №', "Довжина(м)"],
      "values": values,
      "style": "table table-bordered table-hover table-condensed"
    };
  };

  createOpticalIncomeTableData = function(items) {
    var count, field, fields, i, rowdata, values, _i, _j, _len, _len1;

    fields = ["fibers", "rope", "manufacturer", "drum", "length"];
    values = [];
    count = 1;
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      i = items[_i];
      if (i.length !== 0) {
        rowdata = [];
        rowdata.push(count);
        for (_j = 0, _len1 = fields.length; _j < _len1; _j++) {
          field = fields[_j];
          rowdata.push(i[field]);
        }
        values.push(rowdata);
        count++;
      }
    }
    return {
      "title": 'Оптоволокно',
      "headers": ['№', 'Волокон', 'Трос', 'Виробник', 'Барабан', 'Довжина(м)'],
      "values": values,
      "style": "table table-bordered table-hover table-condensed"
    };
  };

  createBoxesStoreTableData = function(items) {
    var count, i, rowdata, values, _i, _len;

    values = [];
    count = 1;
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      i = items[_i];
      if (i.quantity > 0) {
        rowdata = [];
        rowdata.push(count);
        rowdata.push(i.box_name);
        rowdata.push(i.quantity);
        values.push(rowdata);
        count++;
      }
    }
    return {
      "title": 'Коробки на складі',
      "headers": ['№', 'Тип', 'Кількість'],
      "values": values,
      "style": "table table-bordered table-hover table-condensed"
    };
  };

  createpatchpanelesStoreTableData = function(items) {
    var count, i, rowdata, values, _i, _len;

    values = [];
    count = 1;
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      i = items[_i];
      if (i.quantity > 0) {
        rowdata = [];
        rowdata.push(count);
        rowdata.push(i.patchpanel_name);
        rowdata.push(i.quantity);
        values.push(rowdata);
        count++;
      }
    }
    return {
      "title": 'Патч-панелі на складі',
      "headers": ['№', 'Тип', 'Кількість'],
      "values": values,
      "style": "table table-bordered table-hover table-condensed"
    };
  };

  createpatchcordesStoreTableData = function(items) {
    var count, i, rowdata, values, _i, _len;

    values = [];
    count = 1;
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      i = items[_i];
      if (i.quantity > 0) {
        rowdata = [];
        rowdata.push(count);
        rowdata.push(i.patchcord_length);
        rowdata.push(i.patchcord_types);
        rowdata.push(i.quantity);
        values.push(rowdata);
        count++;
      }
    }
    return {
      "title": 'Патч-корди на складі',
      "headers": ['№', 'Довжина', 'Тип', 'Кількість'],
      "values": values,
      "style": "table table-bordered table-hover table-condensed"
    };
  };

  createpigtailsesStoreTableData = function(items) {
    var count, i, rowdata, values, _i, _len;

    values = [];
    count = 1;
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      i = items[_i];
      if (i.quantity > 0) {
        rowdata = [];
        rowdata.push(count);
        rowdata.push(i.pigtails_length);
        rowdata.push(i.pigtails_types);
        rowdata.push(i.quantity);
        values.push(rowdata);
        count++;
      }
    }
    return {
      "title": 'Піг-тейли на складі',
      "headers": ['№', 'Довжина', 'Тип', 'Кількість'],
      "values": values,
      "style": "table table-bordered table-hover table-condensed"
    };
  };

  createsocketsesStoreTableData = function(items) {
    var count, i, rowdata, values, _i, _len;

    values = [];
    count = 1;
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      i = items[_i];
      if (i.quantity > 0) {
        rowdata = [];
        rowdata.push(count);
        rowdata.push(i.sockets_type);
        rowdata.push(i.quantity);
        values.push(rowdata);
        count++;
      }
    }
    return {
      "title": 'Розетки на складі',
      "headers": ['№', 'Тип', 'Кількість'],
      "values": values,
      "style": "table table-bordered table-hover table-condensed"
    };
  };

  createWareHouseLogsTableData = function(items) {
    var count, i, rowdata, values, _i, _len;

    values = [];
    count = 1;
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      i = items[_i];
      rowdata = [];
      rowdata.push(count);
      rowdata.push(i.action);
      rowdata.push(i.name);
      rowdata.push(i.type);
      rowdata.push(i.quantity);
      rowdata.push(i.date.split("T")[0]);
      values.push(rowdata);
      count++;
    }
    return {
      "title": 'Лог змін в обладнанні',
      "headers": ['№', 'Дія', 'Тип', 'Назва', 'Кількість', 'Дата'],
      "values": values,
      "style": "table table-bordered table-hover table-condensed"
    };
  };

  module.exports.createBoxesStoreTableData = createBoxesStoreTableData;

  module.exports.createCopperIncomeTableData = createCopperIncomeTableData;

  module.exports.createOpticalIncomeTableData = createOpticalIncomeTableData;

  module.exports.createsocketsesStoreTableData = createsocketsesStoreTableData;

  module.exports.createpigtailsesStoreTableData = createpigtailsesStoreTableData;

  module.exports.createpatchcordesStoreTableData = createpatchcordesStoreTableData;

  module.exports.createpatchpanelesStoreTableData = createpatchpanelesStoreTableData;

  module.exports.createWareHouseLogsTableData = createWareHouseLogsTableData;

}).call(this);
